version: 2
updates:
- package-ecosystem: composer
  directory: "/01-Login"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.26.1
    - 8.33.1
    - 8.39.0
